open gitlab and sign in account
session 47 gitlab
session 48

stages:
  - build
  - push
  - deploy
  - verify

variables:
  IMAGE_NAME: "notes-app"
  IMAGE_TAG: "latest"
  CONTAINER_NAME: "notes-app-container"
  PORT: "9092"
  HOST: "3.109.133.123"
  DOCKER_USER: "anil2211"

# --------------------- BUILD ---------------------
build_image:
  stage: build
  tags:
    - ec2
  script:
    - echo "======== Building Docker image ========"
    - docker build -t $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG jenkins/notes-app
  only:
    - main

# --------------------- PUSH ----------------------
push_to_dockerhub:
  stage: push
  tags:
    - ec2
  script:
    - echo "======== Logging into Docker Hub ========"
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
    - echo "======== Pushing Image to Docker Hub ========"
    - docker push $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG
  only:
    - main
  dependencies:
    - build_image

# --------------------- DEPLOY --------------------
deploy_container:
  stage: deploy
  tags:
    - ec2
  script:
    - echo "======== Stopping old container (if any) ========"
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true

    - echo "======== Pulling latest image ========"
    - docker pull $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG

    - echo "======== Running new container ========"
    - docker run -d --name $CONTAINER_NAME -p $PORT:80 -v notes-data:/data $DOCKER_USER/$IMAGE_NAME

  only:
    - main
  dependencies:
    - push_to_dockerhub

# --------------------- VERIFY --------------------
verify_app:
  stage: verify
  tags:
    - ec2
  script:
    - echo "======== Verifying application ========"
    - sleep 10
    - curl -s http://$HOST:$PORT | head -n 20
  only:
    - main
  dependencies:
    - deploy_container


# GitLab CI/CD on AWS EC2 with Docker (Beginner → Real‑World)

This guide explains **GitLab CI/CD end‑to‑end** using:

* AWS EC2
* GitLab Runner (Shell executor)
* Docker & Docker Hub
* A real application deployment

You can use this guide **exactly as a real DevOps project**.

---

## 1. Architecture Overview (What We Are Building)

```
Git Push (main)
   ↓
GitLab CI Pipeline
   ↓
Build Docker Image
   ↓
Push Image to Docker Hub
   ↓
Deploy Container on EC2
   ↓
Verify via curl / browser
```

---

## 2. Prerequisites

### Required

* AWS Account
* GitLab Account
* Docker Hub Account
* One EC2 instance (Ubuntu 20.04/22.04)

### EC2 Configuration

* Instance type: t2.micro or t2.medium
* Open ports in Security Group:

  * 22 (SSH)
  * 9092 (Application)

---

## 3. EC2 Setup (Docker + GitLab Runner)

### Step 1: Update EC2

```bash
sudo apt update -y
```

---

### Step 2: Install Docker

```bash
sudo apt install docker.io -y
sudo systemctl enable docker
sudo systemctl start docker
sudo usermod -aG docker ubuntu
```

Verify Docker:

```bash
docker --version
```

---

### Step 3: Install Git

```bash
sudo apt install git -y
git --version
```

---

### Step 4: Install GitLab Runner

```bash
curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
sudo apt install gitlab-runner -y
```

Verify:

```bash
gitlab-runner --version
```

---

### Step 5: Add GitLab Runner to Docker Group

```bash
sudo usermod -aG docker gitlab-runner
```

⚠️ Important: Re-login or reboot EC2 after this step

---

## 4. Create GitLab Runner (Project Level)

### Step 1: Open GitLab Project

```
Project → Settings → CI/CD → Runners → New Project Runner
```

---

### Step 2: Runner Configuration

* Runner Type: **Project runner**
* Tags: **same as .gitlab-ci.yml** (example: `docker-ec2`)
* Executor: **Shell**

Create Runner

---

### Step 3: Register Runner on EC2

Copy the **registration token** and run on EC2:

```bash
sudo gitlab-runner register
```

Provide values:

* GitLab URL: `https://gitlab.com`
* Token: (paste copied token)
* Description: `ec2-docker-runner`
* Tags: `docker-ec2`
* Executor: `shell`

---

### Step 4: Start & Verify Runner

```bash
sudo systemctl enable --now gitlab-runner
sudo systemctl status gitlab-runner
sudo gitlab-runner list
sudo gitlab-runner verify
```

✅ Runner added successfully

---

## 5. Add CI/CD Variables in GitLab

Go to:

```
Project → Settings → CI/CD → Variables
```

Add variables:

| Variable Name   | Value            |
| --------------- | ---------------- |
| DOCKER_USERNAME | anil2211         |
| DOCKER_PASSWORD | Docker Hub Token |
| HOST            | EC2_PUBLIC_IP    |
| PORT            | 9092             |

🔒 Mark **DOCKER_PASSWORD** as *masked & protected*

---

## 6. Docker Hub Setup

### Step 1: Login to Docker Hub

* Username: `anil2211`

### Step 2: Generate Access Token

```
Account Settings → Security → New Access Token
```

Example token:

```

```

Use this token in GitLab CI variable **DOCKER_PASSWORD**

---

## 7. .gitlab-ci.yml (FULL WORKING PIPELINE)

```yaml
stages:
  - build
  - push
  - deploy
  - verify

variables:
  IMAGE_NAME: notes-app

build:
  stage: build
  tags:
    - docker-ec2
  script:
    - docker build -t $DOCKER_USERNAME/$IMAGE_NAME:latest .

push:
  stage: push
  tags:
    - docker-ec2
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
    - docker push $DOCKER_USERNAME/$IMAGE_NAME:latest

 deploy:
  stage: deploy
  tags:
    - docker-ec2
  script:
    - docker rm -f notes || true
    - docker run -d --name notes -p $PORT:9092 -v notes-data:/app/data $DOCKER_USERNAME/$IMAGE_NAME:latest

verify:
  stage: verify
  tags:
    - docker-ec2
  script:
    - sleep 10
    - curl http://$HOST:$PORT
```

---

## 8. Trigger Pipeline

```bash
git add .
git commit -m "GitLab CI Docker deployment"
git push origin main
```

GitLab Pipeline starts automatically 🚀

---

## 9. Application Verification

### Browser

```
http://EC2_PUBLIC_IP:9092
```

### CLI Check

```bash
sudo docker ps
```

---

## 10. Docker Volume Verification (Persistence)

```bash
sudo su -
cd /var/lib/docker/volumes/notes-data/_data
cat notes.txt
```

✅ Confirms persistent data inside container

---

## 11. Common Issues & Fixes

| Issue                    | Fix                               |
| ------------------------ | --------------------------------- |
| Runner not picking job   | Tag mismatch                      |
| Docker permission denied | Add gitlab-runner to docker group |
| Curl fails               | Port not open in SG               |
| Push fails               | Invalid Docker token              |

---

## 12. Interview Ready Explanation

“I implemented GitLab CI/CD using a Shell runner on AWS EC2. The pipeline builds a Docker image, pushes it to Docker Hub, deploys the container on EC2, and verifies it using curl. I used GitLab CI variables for secure credential handling and Docker volumes for persistent storage.”

---

## ✅ Final Outcome

✔ Real DevOps CI/CD project
✔ GitLab Runner + Docker mastery
✔ AWS EC2 deployment
✔ Resume & interview ready

