apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-resources
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-resources
  template:
    metadata:
      labels:
        app: myapp-resources
    spec:
      containers:
      - name: myapp
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"